# Generated by Django 4.1.7 on 2023-03-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_player1_fight_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='host',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fight',
            name='opponent',
            field=models.CharField(default='', max_length=50),
        ),
    ]
