# Generated by Django 4.1.7 on 2023-03-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_fight_host_alter_fight_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='host',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
