# Generated by Django 4.1.7 on 2023-03-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_fight_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='IsRanked',
            field=models.BooleanField(default=False),
        ),
    ]
