# Generated by Django 4.1.7 on 2023-03-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_fight_isranked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='section',
            field=models.CharField(default='all', max_length=50, null=True),
        ),
    ]
