# Generated by Django 4.1.7 on 2023-03-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_fight_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fight',
            name='IsRanked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
